# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acli < Formula
  desc "CLI tool to help with daily DevOps tasks"
  homepage "https://github.com/AidenEyre/acli"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AidenEyre/acli/releases/download/v1.4.0/acli_Darwin_arm64.tar.gz"
      sha256 "804e489004c6d08fd3d8fd932bacf35f3d2f5e0f21dcb0081850ab3e25b346c7"

      def install
        bin.install "acli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AidenEyre/acli/releases/download/v1.4.0/acli_Darwin_x86_64.tar.gz"
      sha256 "fb6847f0508be3eb1e54bda7befe5d1b35a426f35d130186859f983c0ca6a1bb"

      def install
        bin.install "acli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AidenEyre/acli/releases/download/v1.4.0/acli_Linux_arm64.tar.gz"
      sha256 "1d39b1b5bb5b007e7ea16e252b9d43091f479bd115562a396ca7c2c018961402"

      def install
        bin.install "acli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AidenEyre/acli/releases/download/v1.4.0/acli_Linux_x86_64.tar.gz"
      sha256 "e9db90763943cc6d8a6e52ff10a5af8649679f6af1121e2296f29e6b310574c0"

      def install
        bin.install "acli"
      end
    end
  end
end
