# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acli < Formula
  desc "CLI tool to help with daily DevOps tasks"
  homepage "https://github.com/AidenEyre/acli"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AidenEyre/acli/releases/download/v1.4.0/acli_Darwin_arm64.tar.gz"
      sha256 "0372956404a65ec96e21f872a608e761d4dab35d83e101c19a98dc485777cc32"

      def install
        bin.install "acli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AidenEyre/acli/releases/download/v1.4.0/acli_Darwin_x86_64.tar.gz"
      sha256 "ebcbc6956568b45a5feb7cdf89d4c2889e98695a0d6fb7f9831a1be5f80d0cfb"

      def install
        bin.install "acli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/AidenEyre/acli/releases/download/v1.4.0/acli_Linux_x86_64.tar.gz"
      sha256 "d80f1b5638cf91ff6fd12872d70502f4801bfcaa9154d454da281db946b07899"

      def install
        bin.install "acli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AidenEyre/acli/releases/download/v1.4.0/acli_Linux_arm64.tar.gz"
      sha256 "50c58f816a3e0305a228be7765e09e92d7d0386c900d261e29d6c3907505610e"

      def install
        bin.install "acli"
      end
    end
  end
end
